CREATE DATABASE IF NOT EXISTS lab_mysql;
USE lab_mysql;

DROP TABLE IF EXISTS cars;
CREATE TABLE cars (
`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`vin` VARCHAR(255) NOT NULL,
`manufacturer` VARCHAR(255) NOT NULL,
`model` VARCHAR(255) NOT NULL,
`year` INT NOT NULL,
`color` VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS customers;
CREATE TABLE customers (
`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`cust_id` INT NOT NULL UNIQUE,
`cust_name` VARCHAR(255) NOT NULL,
`cust_phone` VARCHAR(255),
`cust_email` VARCHAR(255),
`cust_address` VARCHAR(255),
`cust_city` VARCHAR(255),
`cust_state` VARCHAR(255),
`cust_country` VARCHAR(255),
`cust_zipcode` VARCHAR(255)
);

DROP TABLE IF EXISTS salespersons;
CREATE TABLE salespersons (
`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`staff_id` BIGINT NOT NULL UNIQUE,
`name` VARCHAR(255) NOT NULL,
`store` VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS invoices;
CREATE TABLE invoices (
`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`invoice_number` INT NOT NULL UNIQUE,
`date` VARCHAR(255) NOT NULL,
`car` BIGINT NOT NULL,
`customer` BIGINT NOT NULL,
`salesperson` BIGINT NOT NULL
);

